### ISSUE TITLE
Invert Videostream

### ISSUE THREAD

**Issue by minimalisticMe** [sabitertan/BlazorBarcodeScanner#19]
Hi,

this library works great with regular barcodes with white background and black QR-Image.
I have a scenario, where this is inverted, meaning dark background and bright QR-Image.

Is it possible to switch between "normal" scan and "inverted" scan like described here: [https://stackoverflow.com/questions/42339540/how-to-scan-white-on-black-barcode-android-inverted-can](https://stackoverflow.com/questions/42339540/how-to-scan-white-on-black-barcode-android-inverted-can) with BlazorBarcodeScanner?

**Comment by sabitertan** [comment]
Just referencing for later decision : https://github.com/zxing-js/library/issues/135#issuecomment-470430181

**Comment by abt-vahap-demir** [comment]
@minimalisticMe I have modified getLuminanceSource() in zxingjs.index.min.js as follows. That works now.

```
getLuminanceSource()
{
    const d=new Date();
    let seconds=d.getSeconds();
    let flag=seconds % 2;
    if (flag==0)
    {
        return this.source.invert();
    }
    else
    {
        return this.source;
    }
}
```
