### ISSUE TITLE
Provide Completed Event for start

### ISSUE THREAD

**Issue by nssidhu** [sabitertan/BlazorBarcodeScanner#21]
Currently when we click start it takes a while before the Video appears. would be nice to have an event when the load is completed, so that we can display some custom content and take down the custom content after load is completed

**Comment by sabitertan** [comment]
Fixed in [c16361](https://github.com/sabitertan/BlazorBarcodeScanner/commit/c163615ad2e4a4469a940825c19b95b14842e53a)
