### ISSUE TITLE
StartCameraAutomatically crashes if permission not granted

### ISSUE THREAD

**Issue by Hackmodford** [sabitertan/BlazorBarcodeScanner#24]
I expect this just needs to be in a try/catch block in the `OnInitializedAsync` method.

Going the extra mile, it would be nice to have a property that I can use to check if the permission is granted to modify the UI accordingly.

**Comment by sabitertan** [comment]
f66bc6dcd85eb640a8ccd7328bb1ed8fe280d2b9
