### ISSUE TITLE
Error Bounderies does not work 

### ISSUE THREAD

**Issue by babaktaremi** [sabitertan/BlazorBarcodeScanner#28]
I have a scanner component like this 

'''html
<ErrorBoundary>
    <BlazorBarcodeScanner.ZXing.JS.BarcodeReader
        Title=""
        StartCameraAutomatically="true"
        ShowStart="false"
        ShowReset="false"
        ShowToggleTorch="false"
        ShowVideoDeviceList="false"
        VideoWidth="base.PageWidth"
        VideoHeight="base.PageHeight"
        OnBarcodeReceived="Callback"
        ShowResult="false"/>
</ErrorBoundary>

'''

for some reason the error boundery won't work. Any ideas?

**Comment by sabitertan** [comment]
@babaktaremi I am not sure what do you mean "error boundary won't work". Can you please create a demo repo so we can look at it?

**Comment by sabitertan** [comment]
f66bc6dcd85eb640a8ccd7328bb1ed8fe280d2b9
