### ISSUE TITLE
InvalidOperationException

### ISSUE THREAD

**Issue by cbrownmobile** [sabitertan/BlazorBarcodeScanner#3]
I have built this project as Webassembly and as server (net5). On my dev system both types work fine in visual studio testing .

I published to IIS on my dev system and can run both in the local browser (edge) and it works . 

If I use another computer on the same network and open the app in browser (edge) ,  on Webassembly I get error but I can't get any error details, just say reload.     

on server version , I get error below , 
I set the ASPNETCORE_ENVIRONMENT  to Development to see error 

InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.

what would server side code change be to use OnAfterRenderAsync 

I also tested by connecting to my dev system using an android phone browser and iPad browser , received same error on server, webassembly just said reload.

**Comment by sabitertan** [comment]
@cbrownmobile 
Thanks for feedback.
Library doesn't support ServerPrerender mode at this moment.
As a workaround edit your serverside project's _Host.chtml file to try other modes if possible:
change: `<component type="typeof(App)" render-mode="ServerPrerendered" />`
with `<component type="typeof(App)" render-mode="Server" />`
 I updated library using Net5.0 too.

**Comment by cbrownmobile** [comment]
Thank you 

 

Clark Brown

 <mailto:cbrownmobile@gmail.com> cbrownmobile@gmail.com

Mobile | (901) 335-2596
