### ISSUE TITLE
How to Display Error message for No Device Found or Permission not granted ?

### ISSUE THREAD

**Issue by nssidhu** [sabitertan/BlazorBarcodeScanner#35]
I see that in your demo you are able to display error Message , when permission is not provided.
but there is not information on how to do that.
Can you provide information on both the scenario
1) There are no vide device , display appropriate message
2) user has not granted permission, display appropriate message

**Comment by sabitertan** [comment]
If similar functionality needed here is where it is taking care of  https://github.com/sabitertan/BlazorBarcodeScanner/blob/master/BlazorBarcodeScanner.ZXing.JS/BarcodeReaderInterop.cs
Not related to library's functionality, closing.
