### ISSUE TITLE
StopDecoding after OnBarcodeReceived

### ISSUE THREAD

**Issue by MentYy** [sabitertan/BlazorBarcodeScanner#39]
Hi,

How can I automatically stop decoding after reading code? It work fine if I read and stop manually but when trying to StopDecoding after OnBarcodeReceived I get an System.Exception error.

private string LocalBarcodeText;

    private void LocalReceivedBarcodeText(BarcodeReceivedEventArgs args)
    {
        this.LocalBarcodeText = args.BarcodeText;
        StateHasChanged();
        _reader.StopDecoding();
    }

Am I missing something?

Thank you.

**Comment by sabitertan** [comment]
`private void LocalReceivedBarcodeText(BarcodeReceivedEventArgs args)
{
    this.LocalBarcodeText = args.BarcodeText;
    _reader.StopDecoding();
    StateHasChanged();
}`
Can you try to stop it before triggering StateHasChanged?
