### ISSUE TITLE
Feature Request: Camera Light

### ISSUE THREAD

**Issue by Kylar182** [sabitertan/BlazorBarcodeScanner#4]
You can see the request [here](https://github.com/zxing-js/library/issues/267) in the JS Library. It's available on the Angular Version and it's also available on Quagga JS [here](https://serratus.github.io/quaggaJS/).

The Reason for the light is to make the camera read the QR / Barcodes easier. Since it's measuring light and dark (Black / White), the camera's light can help differentiate in darker rooms / outdoor evenings.

**Comment by sabitertan** [comment]
@Kylar182 Can you please clone repo and test "Toggle Torch" functionality?

**Comment by uniederer** [comment]
Even though it's not my feature request, I would like to give you feedback: On my Android phone (Android 11) setTorchOn/Off works. Yet toggle torch only turns it on but never turns it off again. I didn't investigate in that much though.

**Comment by sabitertan** [comment]
@uniederer Thank you for testing!
As we argued on this issue on zxing-js too https://github.com/zxing-js/library/issues/267#issuecomment-816952247
"torch: off" is not part of standard yet https://github.com/w3c/mediacapture-image/issues/275 
:)

**Comment by uniederer** [comment]
Very odd that this has been "forgotten" in the standard. I'm quite a fan of symmetric APIs (i.e. whatever you can trigger in one direction, can be reverted...)

In my case I'm able to turn off the torch using the dedicated API call, triggering `mediaStreamSetTorch(this.codeReader.stream.getVideoTracks()[0], false);`. It looks to me as if something goes south in that code section here, where you try to determine the torch's status. 
```
if (track !== null) {
    let torchStatus = track.getConstraints().torch ? false: true;
    mediaStreamSetTorch(track, torchStatus);
}
```
Unfortunately I'm currently not setup to debug the web app on my Android phone...

**Comment by eehakkin** [comment]
> Very odd that this has been "forgotten" in the standard. I'm quite a fan of symmetric APIs (i.e. whatever you can trigger in one direction, can be reverted...)

It hasn't been "forgotten" in the standard. The API is symmetric.

> In my case I'm able to turn off the torch using the dedicated API call, triggering `mediaStreamSetTorch(this.codeReader.stream.getVideoTracks()[0], false);`.

So as you can see it works symmetrically.

> It looks to me as if something goes south in that code section here, where you try to determine the torch's status.
> 
> ```
> if (track !== null) {
>     let torchStatus = track.getConstraints().torch ? false: true;

This tests if `track.applyConstraints({torch: true})` call. There is never such call thus `track.getConstraints().torch` is always undefined (I think) and thus `torchStatus` is always `true`. This should probably be 
```js
    let torchStatus = !track.getSettings().torch;
```
so that it uses the current torch setting and inverts that.

>     mediaStreamSetTorch(track, torchStatus);
> }
> ```
> 
> Unfortunately I'm currently not setup to debug the web app on my Android phone...

**Comment by sabitertan** [comment]
@eehakkin Thanks for input, that helps for toggle function. But we weren't able to turn it off (using only setTorchOff function) on Chrome 87. I am not sure if that fixed on Chrome 90 now, because it is working now.

**Comment by uniederer** [comment]
> > Very odd that this has been "forgotten" in the standard. I'm quite a fan of symmetric APIs (i.e. whatever you can trigger in one direction, can be reverted...)
> 
> It hasn't been "forgotten" in the standard. The API is symmetric.
This was a reply to @sabitertan s statement, that this was not part of the standard. I wrote the rest of my post exactly because of the symmetric experience I described.

But thanks anyway for adding the exact bit on how to toggle the torch status, for which that I hadn't the time to investigate.
