### ISSUE TITLE
Does not work in the Blazor Server Project

### ISSUE THREAD

**Issue by nssidhu** [sabitertan/BlazorBarcodeScanner#42]
When including it in the server project, I don't receive decoded barcode.
It works perfect in the Blazor WebAssembly Project though.
![image](https://user-images.githubusercontent.com/3267605/183322222-1a0a29bc-96d2-45d5-86da-20b96874134f.png)

I am using it in .NET 6.0

**Comment by vse3211** [comment]
.NET 5.0
NULL Exception on blazor server

**Comment by sabitertan** [comment]
Dropped 5.0 support, please use .NET6 + .
