### ISSUE TITLE
No OnCodeReceived to receive value

### ISSUE THREAD

**Issue by sallen23322** [sabitertan/BlazorBarcodeScanner#43]
Hello,
the following combination errors:
    OnCodeReceived="LocalReceivedBarcodeText"

<BlazorBarcodeScanner.ZXing.JS.BarcodeReader Title=""
                                             @ref="reader"
                                              OnCodeReceived="LocalReceivedBarcodeText"
                                             ShowResult="true"
                                             StartCameraAutomatically="true"
                                             ShowStart="true"
                                             ShowReset="true"
                                             ShowToggleTorch="false"
                                             ShowVideoDeviceList="false"
                                             VideoWidth="300"
                                             VideoHeight="200" />
System.InvalidOperationException: Object of type 'BlazorBarcodeScanner.ZXing.JS.BarcodeReader' does not have a property matching the name 'OnCodeReceived'.

**Comment by sabitertan** [comment]
supposed to be OnBarcodeReceived
