### ISSUE TITLE
Let us help? 

### ISSUE THREAD

**Issue by IDGC-ESC** [sabitertan/BlazorBarcodeScanner#52]
I tried to create a pull request to help contribute to the fixing of #49 but was unable to authenticate to the repo. If you will update the settings to allow branches and pull requests to be created, we can help with the work required to fix issues, leaving you to simply review and approve. For for thought; just wanting to help a good offering where I can 😊

**Comment by sabitertan** [comment]
I am not sure what you are referring, you should be able to fork and create PR right now, just like other contributors did before.

**Comment by IDGC-ESC** [comment]
My bad lol... For some reason I was thinking that I needed to clone and make a branch as if we work together >_< I'll stop being a n00b now haha
