### ISSUE TITLE
MAUI Android component not refreshing video feed, MAUI Windows works fine 

### ISSUE THREAD

**Issue by chaitanyakale** [sabitertan/BlazorBarcodeScanner#57]
This is excellent work, but I'm unable to use this on MAUI Android as video feed display requires constant touch input to render updates to BlazorWebView. Is there any workaround?

**Comment by chaitanyakale** [comment]
This issue is related to a bug in Android WebView. https://github.com/react-native-webview/react-native-webview/issues/2698

**Comment by sabitertan** [comment]
No matter what if you are on mobile devices, I recommend using different libraries that are closer to metal:

https://github.com/hjam40/Camera.MAUI

https://capawesome.io/plugins/mlkit/barcode-scanning/
