### ISSUE TITLE
Blazor WebAssembly hata

### ISSUE THREAD

**Issue by alieymur** [sabitertan/BlazorBarcodeScanner#58]
Blazor WebAssembly de kodun çalıştığı cihazda kamera yoksa  _reader.StartDecoding() kodu "An unhandled error has occurred." hatasının gözükmesine sebep oluyor.

**Comment by sabitertan** [comment]
Resolved with : https://github.com/sabitertan/BlazorBarcodeScanner/commit/80f6e507b4ece26b6e3e643289da47081c6a3395
